version: 0.0
os: linux
hooks:
  BeforeInstall:
  - location: /scripts/deleta-aplicacao.sh
  ApplicationStart:
  - location: /scripts/reinicia-tomcat.sh
files:
  - source: target/alura-aws
    destination: /var/lib/tomcat8/webapps/loja
